### ISSUE TITLE
Who is publishing "/camera_settings"?

### ISSUE THREAD

**Issue by carcormir** [georgealexakis/multispectral_processing#2]
Hey!
I was checking out your project and tried to understand how it works but I run into this issue. I cannot figure out who is publishing in the "/camera_settings" topic.
More specifically, line 85 of the [band_separator.py](https://github.com/georgealexakis/multispectral_processing/blob/master/src/band_separator.py)
I thought it would be something coming from the ueye_cam node but I could not find any topic named /camera_settings.

Any inputs on this?

Thanks in advance!

C

**Comment by georgealexakis** [comment]
Hello.

Topic /camera_settings is used for the connection with an external controller of the camera. For instance, during processing, we want to enable the crosstalk correction or flatfield correction with our smartphone by using rosbridge. Of course you can ignore it and you can use OpenCV triggers. See line 954 of the [band_separator.py](https://github.com/georgealexakis/multispectral_processing/blob/b7746720fd81bb550e026e6db20e5ad9825db57e/src/band_separator.py#L954).

**Comment by carcormir** [comment]
Thanks for the info!
